---
title: "P8105_hw3_as5697"
author: "Apoorva Srinivasan"
date: "10/14/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
 collapse = TRUE,
  fig.width = 10,
  fig.asp = .6,
  out.width = "90%"
)

library(tidyverse)
library(readxl)
library(p8105.datasets)
library(ggplot2)
library(ggridges)
library(patchwork)
library(viridis)


theme_set(theme_bw() + theme(legend.position = "bottom"))
```


#Problem 1

###1.1

```{r}
data(brfss_smart2010)
```

```{r tidy_brfss}
brfss = brfss_smart2010 %>% 
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>%
  filter(response %in% c("Excellent", "Very good", "Good", "Fair", "Poor")) %>% 
  rename(state = locationabbr, county = locationdesc) %>%
  mutate(response = as.factor(response)) %>% 
  mutate(
    response = fct_relevel(response, c("Excellent", "Very good", "Good", "Fair", "Poor"))
    )
```


###1.2

In 2002, which states were observed at 7 locations?


```{r}
brfss %>% 
  filter(year == 2002) %>% 
  group_by(state) %>% 
  summarize(n_locations = n_distinct(county)) %>% 
  filter(n_locations == 7) %>%
  head()
```

###1.3

Make a “spaghetti plot” that shows the number of locations in each state from 2002 to 2010.


```{r p1.3}
brfss %>%
  group_by(year, state) %>%
  summarize(num_locations = n()) %>%
  ggplot(aes(x = year, y = num_locations, color = state)) + 
  labs(
    title = "Spaghetti plot of number of locations in each state from 2002 to 2010",
    x = "Year",
    y = "Number of locations") +
  geom_line() + 
  theme(legend.position = "right") +
  scale_color_viridis(discrete = TRUE) 
```


###1.4

Make a table showing, for the years 2002, 2006, and 2010, the mean and standard deviation of the proportion of “Excellent” responses across locations in NY State.


```{r p1.4}
brfss %>%
  spread(key = response, value = data_value) %>%
  janitor::clean_names() %>%
  filter(year == "2002" | year == "2006" | year == "2010") %>% 
  group_by(year, state) %>%
  summarize(excellent_mean = mean(excellent, na.rm = TRUE), 
            excellent_SD = sd(excellent, na.rm = TRUE)) %>%
  filter(state == "NY") %>%
  knitr::kable(digits = 1)
```


###1.5

```{r p1.5}
brfss %>% 
  group_by(year, state, response) %>% 
  summarize(average = mean(data_value, na.rm = TRUE)) %>% 
  ggplot(aes(x = year, y = average, group = year, color = response)) + 
  geom_boxplot() + 
  facet_grid(~ response) +
  labs(title = "Distribution of State Level Averages Over Time", x = "Year", y = "Mean Proportions") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
  
```
